version: "3"
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "rasa"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"

  rasa_actions:
    build:
      context: .
      dockerfile: rasa_actions.Dockerfile
    volumes:
      - .:/app/
    ports:
      - "5055:5055"

  rasa_listener:
    build:
      context: .
      dockerfile: rasa_listener.Dockerfile
    volumes:
      - .:/app/
    ports:
      - "5005:5005"
