version: "3"
services:
  rasa_actions:
    build:
      context: .
      dockerfile: rasa_actions.Dockerfile
    volumes:
      - .:/app/
    ports:
      - "5055:5055"

  rasa_listener:
    build:
      context: .
      dockerfile: rasa_listener.Dockerfile
    volumes:
      - .:/app/
    ports:
      - "5005:5005"
